source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

target 'ZFNativeAdsManagerDemo' do

    pod 'Masonry'
    pod 'FBAudienceNetwork'
    pod 'Firebase/Core'
    pod 'Firebase/AdMob'

end
